---
- name: Create public_html directory
  file:
    path: /home/otsmanager/www/public_html
    owner: otsmanager
    group: otsmanager
    mode: 0755
    state: directory

- name: Make public_html accessible to nginx
  file:
    path: /home/otsmanager
    mode: o+x
    state: directory
